config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "domains#search"  

  resources :users
  resources :registrants
  resources :details
  resources :domains
  resources :orders
  resources :payment_transactions

  get 'search/result' => 'domains#result', :as => 'result_page'
  # get 'receipt' => 'domains#result', :as => 'result_page'
  
  get '/payment/paypal', to: 'payments#paypal'
  post '/payment/create', to: 'payments#create'
  post '/payment/execute', to: 'payments#execute'

  #post '/payment/create' => 'payments#paypal', :as => 'payment_page'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/registrant.rb
class Registrant < ApplicationRecord
    # has_many :domains
    # belongs_to :domains
    has_one :detail
    accepts_nested_attributes_for :detail

    has_one :domain
    accepts_nested_attributes_for :domain
end

app/controllers/registrants_controller.rb
class RegistrantsController < ApplicationController
  before_action :set_registrant, only: [:show, :edit, :update, :destroy]

  # GET /registrants
  # GET /registrants.json
  def index
    @registrants = Registrant.all
  end

  # GET /registrants/1
  # GET /registrants/1.json
  def show
  end

  # GET /registrants/new
  def new
    @registrant = Registrant.new
  end

  # GET /registrants/1/edit
  def edit
  end

  # POST /registrants
  # POST /registrants.json
  def create
    @timestamp = '%10.6f' % Time.now.to_f
    @handle = @timestamp.sub('.', '')

    @registrant = Registrant.new(registrant_params)
    @build_detail_temp = @registrant.build_detail(registrant_params[:detail_attributes])

    @registrant.handle = @handle

    # raise @reg_temp.inspect
    @order = Order.create(user_id:current_user.id)
        @order.save

    # @domain = current_user.domains.new(domain_params)
    @build_domain_temp = @registrant.build_domain(registrant_params[:domain_attributes])

    @build_domain_temp.user_id = current_user.id
    @build_domain_temp.registrant_id = @registrant.id
    @build_domain_temp.order_id = @order.id

    respond_to do |format|
      if @registrant.save
        @build_detail_temp.save
        @build_domain_temp.save

        format.html { redirect_to domains_path, notice: 'Registrant was successfully created.' }
        format.json { render :show, status: :created, location: @registrant }
      else
        format.html { render :new }
        format.json { render json: @registrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registrants/1
  # PATCH/PUT /registrants/1.json
  def update
    respond_to do |format|
      if @registrant.update(registrant_params)
        format.html { redirect_to @registrant, notice: 'Registrant was successfully updated.' }
        format.json { render :show, status: :ok, location: @registrant }
      else
        format.html { render :edit }
        format.json { render json: @registrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registrants/1
  # DELETE /registrants/1.json
  def destroy
    @registrant.destroy
    respond_to do |format|
      format.html { redirect_to registrants_url, notice: 'Registrant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registrant
      @registrant = Registrant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def registrant_params
      params.require(:registrant).permit(
        :handle,
        detail_attributes: [
          :first_name, :last_name, :organization, :contact_number, :address
        ],
        domain_attributes: [
          :domain_name, 
          :period, 
          :registration_date, 
          :expiration_date,
          :handle
        ]
      )
    end
end

app/helpers/registrants_helper.rb
module RegistrantsHelper
end

app/views/registrants/_form.html.erb
<%= form_with(model: registrant, local: true) do |form| %>
  <% if registrant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(registrant.errors.count, "error") %> prohibited this registrant from being saved:</h2>

      <ul>
      <% registrant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>Registrant Details:</p>
  <%= form.fields_for :detail_attributes, @registrant.detail do |detail| %>
    <%= detail.label :first_name %>
    <%= detail.text_field :first_name %>

    <%= detail.label :last_name %>
    <%= detail.text_field :last_name %>

    <%= detail.label :organization %>
    <%= detail.text_field :organization %>

    <%= detail.label :contact_number %>
    <%= detail.text_field :contact_number %>

    <%= detail.label :address %>
    <%= detail.text_field :address %>
  <% end %>
<hr>
  <p>Domain Details:</p>
  <%= form.fields_for :domain_attributes, @registrant.domain do |domain| %>
  <div class="field">
    <%= domain.label :domain_name, :value => params[:domain_name]  %>
    <%= domain.text_field :domain_name %>
  </div>

  <div class="field">
    <%= domain.label :period %>
    <%= domain.select :period, ['3 months', '1 year', '2 years', '5 years', '10 years'] %>
  </div>

  <div class="field">
    <%= domain.label :registration_date %>
    <%= domain.datetime_select :registration_date %>
  </div>

  <div class="field">
    <%= domain.label :expiration_date %>
    <%= domain.datetime_select :expiration_date %>
  </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<div id="paypal-checkout"></div>
<script src="https://www.paypalobjects.com/api/checkout.js"></script>
<script>
  paypal.Button.render({
    env: "sandbox",
    client: {
      sandbox: "AW4I8tHeTC_xdRHrcvpgD2RgBHC-QlhnNO3uP_ZyUjpCanJbxbMvM3qI9nbnSv2ZtrMf_jNOZMuJV055"
    },
    style: {
      layout: 'vertical',
      size:  'medium',
      shape: 'rect',
      color: 'blue',
    },
    commit: true,
    funding: {
      allowed: [paypal.FUNDING.CARD],
      disallowed: [paypal.FUNDING.CREDIT]
    },
    payment: function(data, actions) {
      var domain_name_temp = document.getElementById("registrant_domain_attributes_domain_name").value
      var period_temp = document.getElementById("registrant_domain_attributes_period").value
      params = {domain_name: domain_name_temp, period: period_temp};
      
      createPath = "http://127.0.0.1:3000/payment/create"
      return actions.request.post(createPath, params).then(function(response) {
        console.log(response);
        return response.id;
      });
    },
    onAuthorize: function(data, actions) {
      var domain_name_temp = document.getElementById("registrant_domain_attributes_domain_name").value
      var period_temp = document.getElementById("registrant_domain_attributes_period").value

      params = {
          payment_id: data.paymentID, 
          payer_id: data.payerID,
          domain_name: domain_name_temp, 
          period: period_temp
          }

      executePath = "http://127.0.0.1:3000/payment/execute"
      return actions.request.post(executePath, params).then(function(response) {
        if (response.payment_state == "approved") {
          javascript:window.location.href = 'http://127.0.0.1:3000' // Replace this with your successful registration page
          
        }
      });
    },
    onError: function (err) {
      alert('Error!');
    }
  }, '#paypal-checkout');

</script>

app/views/registrants/edit.html.erb
<h1>Editing Registrant</h1>

<%= render 'form', registrant: @registrant %>

<%= link_to 'Show', @registrant %> |
<%= link_to 'Back', registrants_path %>

app/views/registrants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registrants</h1>

<table>
  <thead>
    <tr>
      <th>Contact handle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registrants.each do |registrant| %>
      <tr>
        <td><%= registrant.handle %></td>
        <td><%= link_to 'Show', registrant %></td>
        <td><%= link_to 'Edit', edit_registrant_path(registrant) %></td>
        <td><%= link_to 'Destroy', registrant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registrant', new_registrant_path %>

app/views/registrants/new.html.erb
<h1>Domain Registration Form</h1>

<%= render 'form', registrant: @registrant %>

<%= link_to 'Back', registrants_path %>

app/views/registrants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Registrant handle:</strong>
  <%= @registrant.handle %>
</p>

<p>
  <strong>First Name:</strong>
  <%= @registrant.detail.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @registrant.detail.last_name %>
</p>


<p>
  <strong>Organization:</strong>
  <%= @registrant.detail.organization %>
</p>


<p>
  <strong>Address:</strong>
  <%= @registrant.detail.address %>
</p>


<%= link_to 'Edit', edit_registrant_path(@registrant) %> |
<%= link_to 'Back', registrants_path %>