config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "domains#search"  

  resources :users
  resources :registrants
  resources :details
  resources :domains
  resources :orders
  resources :payment_transactions

  get 'search/result' => 'domains#result', :as => 'result_page'
  # get 'receipt' => 'domains#result', :as => 'result_page'
  
  get '/payment/paypal', to: 'payments#paypal'
  post '/payment/create', to: 'payments#create'
  post '/payment/execute', to: 'payments#execute'

  #post '/payment/create' => 'payments#paypal', :as => 'payment_page'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_one :domain
  has_one :payment_transaction
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :set_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.all
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
  end

  # GET /domains/new
  def new
    @order = Order.new
  end

  # GET /domains/1/edit
  def edit
  end

  # POST /domains
  # POST /domains.json
  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to @order, notice: 'Order is added'
    else
      render 'new'
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @domain, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(
        :user_id, 
      )
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/edit.html.erb
<h1>Edit Domain</h1>


<%= render partial: 'domains/partials/form' %>

app/views/orders/index.html.erb
<div class="main">
  <h1>Orders</h1>

  <div class="">


    <div class="">
      <table>
        <tr>
          <th>Order</th>
          <th>User</th>
          <th>Domain</th>
        </tr>
        <% @orders.each do |order| %>
          <tr>
            <td>
              <%= order.id %>
            </td>
            <td>
              <%= order.user %>
            </td>
            <td>
              <%= order.domain %>
            </td>
            <td>
              <%= link_to 'Show', order_path(order.id) %>
            </td>
            <td>
              <%= link_to 'Delete', order_path(order.id), method: :delete %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
    <%= link_to 'Create new Order', new_order_path %>
  </div>
</div>

app/views/orders/new.html.erb
<h1>New Domain</h1>


<%= render partial: 'domains/partials/form' %>

app/views/orders/show.html.erb
<h1>Show</h1>


<p>Domain name: <%= @domain.name %></p>
<p>Registration Date: <%= @domain.registration_date %></p>
<p>Expiration Date: <%= @domain.expiration_date %></p>
<p>Registered to: <%= @domain.user.full_name %></p>

<%= link_to 'Edit Domain', edit_domain_path(@domain.id) %>
<%= link_to 'Back', domains_path %>