config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "domains#search"  

  resources :users
  resources :registrants
  resources :details
  resources :domains
  resources :orders
  resources :payment_transactions

  get 'search/result' => 'domains#result', :as => 'result_page'
  # get 'receipt' => 'domains#result', :as => 'result_page'
  
  get '/payment/paypal', to: 'payments#paypal'
  post '/payment/create', to: 'payments#create'
  post '/payment/execute', to: 'payments#execute'

  #post '/payment/create' => 'payments#paypal', :as => 'payment_page'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/domain.rb
class Domain < ApplicationRecord
	belongs_to :user
	belongs_to :order
	belongs_to :registrant
	
	has_one :domain_price
	accepts_nested_attributes_for :domain_price
	

	def self.search(search)
		#search is the domain name
		if search #if there is an input
			domain = Domain.find_by(domain_name: search)
			if domain
				self.where(id: domain)
			end
		end
	end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_domain, only: [:show, :edit, :update, :destroy]

  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
  end


  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
  end

  # POST /domains
  # POST /domains.json
  def create
    # create registrant -> create order -> create domain
    @order = Order.create(user_id:current_user.id)
    @order.save

    if @order.save
      puts "order created with id #{@order.id}"
    else
      puts 'order creation failed'
    end

    @domain = current_user.domains.new(domain_params)

    @domain.user_id = current_user.id
    @domain.registrant_id = Registrant.last.id
    @domain.order_id = @order.id

    # create an order first
    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render :show, status: :created, location: @domain }
      else
        format.html { render :new }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { render :show, status: :ok, location: @domain }
      else
        format.html { render :edit }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to domains_url, notice: 'Domain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    #insert input validation here
  end

  def result
    @renew_flag = false
    @available_flag = false

    if current_user.domains.search(params[:search]) != nil #there are domains available for renewal for current user
      @domains = current_user.domains.search(params[:search]) #return domains of user
      @renew_flag = true
    else #no registered domains under current user, check in epp if available
          @domains = Domain.search(params[:search])
          flash.now[:notice] = 'Domain available!'
          @available_flag = true

          #temp variable to pass input to register model
          @search_temp = params[:search]

      		# host      = "172.16.46.55"
          # username  = "testmrocafort"
          # password  = "Password123"
        
          # client = EPP::Client.new username, password, host
        
          # #epp checker for domain availability
          # command   = EPP::Domain::Check.new(params[:search])
          # response  = client.check command
          # check     = EPP::Domain::CheckResponse.new response
        
          # if check.available? #if available, show register link to user (use a flag to be used in view)
          #   @domains = Domain.search(params[:search])
          #   flash.now[:notice] = 'Domain available!'
          #   @available_flag = true

          #   #temp variable to pass input to register model
          #   @search_temp = params[:search]
          # else #if not available, do nothing
          #   redirect_to '/'
          #   flash[:notice] = 'Domain unavailable!'
          # end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def domain_params
      params.require(:domain).permit(
        :domain_name, 
        :period, 
        :registration_date, 
        :expiration_date,
        :handle, 
        :search,
        domain_price_attributes: [
          :id,
          :price,
          :price_cents,
          :price_currency
        ]
      )
    end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_form.html.erb
<%= form_with(model: domain, local: true) do |form| %>
  <% if domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% domain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :domain_name %>
    <%= form.text_field :domain_name %>
  </div>

  <div class="field">
    <%= form.label :period %>
    <%= form.select :period, ['3 months', '1 year', '2 years', '5 years', '10 years'] %>
  </div>

  <div class="field">
    <%= form.label :registration_date %>
    <%= form.datetime_select :registration_date %>
  </div>

  <div class="field">
    <%= form.label :expiration_date %>
    <%= form.datetime_select :expiration_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

<div id="paypal-checkout"></div>
<script src="https://www.paypalobjects.com/api/checkout.js"></script>
<script>
  paypal.Button.render({
    env: "sandbox",
    client: {
      sandbox: "AW4I8tHeTC_xdRHrcvpgD2RgBHC-QlhnNO3uP_ZyUjpCanJbxbMvM3qI9nbnSv2ZtrMf_jNOZMuJV055"
    },
    style: {
      layout: 'vertical',
      size:  'medium',
      shape: 'rect',
      color: 'blue',
    },
    commit: true,
    funding: {
      allowed: [paypal.FUNDING.CARD],
      disallowed: [paypal.FUNDING.CREDIT]
    },
    payment: function(data, actions) {
      var domain_name_temp = document.getElementById("domain_domain_name").value
      var period_temp = document.getElementById("domain_period").value
      params = {domain_name: domain_name_temp, period: period_temp};
      
      createPath = "http://127.0.0.1:3000/payment/create"
      return actions.request.post(createPath, params).then(function(response) {
        console.log(response);
        return response.id;
      });
    },
    onAuthorize: function(data, actions) {
      var domain_name_temp = document.getElementById("domain_domain_name").value
      var period_temp = document.getElementById("domain_period").value

      params = {
        payment_id: data.paymentID, 
        payer_id: data.payerID
        domain_name: domain_name_temp, 
        period: period_temp
      }

      executePath = "http://127.0.0.1:3000/payment/execute"
      return actions.request.post(executePath, params).then(function(response) {
        if (response.payment_state == "approved") {
          javascript:window.location.href = 'http://127.0.0.1:3000' // Replace this with your successful registration page
          
        }
      });
    },
    onError: function (err) {
      alert('Error!');
    }
  }, '#paypal-checkout');

</script>

app/views/domains/_renew_form.html.erb
<h3>Renew <%= domain.domain_name %></h3>

<%= form_with(model: domain, local: true) do |form| %>
  <% if domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% domain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :period %>
    <%= form.select :period, ['3 months', '1 year', '2 years', '5 years', '10 years'] %>
  </div>

  <div class="field">
    <%= form.label :registration_date %>
    <%= form.datetime_select :registration_date %>
  </div>

  <div class="field">
    <%= form.label :expiration_date %>
    <%= form.datetime_select :expiration_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<h1>Renew Domain</h1>

<%= render 'renew_form', domain: @domain %>

<%= link_to 'Show', @domain %> |
<%= link_to 'Back', domains_path %>

app/views/domains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Domains</h1>

<table>
  <thead>
    <tr>
      <th>Domain name</th>
      <th>Period</th>
      <th>Registration date</th>
      <th>Expiration date</th>
      <th>Owner</th>
      <th>Registrant</th>
      <th>Order ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @domains.each do |domain| %>
      <tr>
        <td><%= domain.domain_name %></td>
        <td><%= domain.period %></td>
        <td><%= domain.registration_date %></td>
        <td><%= domain.expiration_date %></td>
        <td><%= domain.user.first_name %></td>
        <td><%= link_to "#{domain.registrant.handle}", registrant_path(domain.registrant) %></td>
        <td><%= domain.order.id %></td>
        <td><%= link_to 'Show', domain %></td>
        <td><%= link_to 'Edit', edit_domain_path(domain) %></td>
        <td><%= link_to 'Destroy', domain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Domain', new_domain_path %>

app/views/domains/new.html.erb
<h1>Register Domain</h1>

<%= render 'form', domain: @domain %>

<%= link_to 'Back', domains_path %>

app/views/domains/result.html.erb
<% if @renew_flag == true %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Period</th>
        <th>Registration Date</th>
        <th>Expiration Date</th>
        <th>Owner</th>
        <th colspan="5"></th>
      </tr>
    </thead>
    
    <tbody>
      <% @domains.each do |domain| %>
        <tr>
          <td><%= domain.domain_name %></td>
          <td><%= domain.period %></td>
          <td><%= domain.registration_date %></td>
          <td><%= domain.expiration_date %></td>
          <td><%= domain.user.first_name %></td>
          <td><%= link_to 'Click here to renew', edit_domain_path(domain) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <% if @available_flag == true %>

        <%= link_to 'Domain available. Do you want to register this domain?', new_registrant_path({:domain_name => @search_temp}) %>

  <% else %>
    Domain unavailable.
  <% end %>
<% end %>

app/views/domains/search.html.erb
<h3>Welcome, <%= current_user.first_name %></h3>

<%= form_tag(result_page_path, method: :get) do %>
  <%= label_tag(:search, "Enter Domain:") %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag("Search") %>
<% end %>

<br>

<% if user_signed_in? %>
  <%= link_to('Log Out', destroy_user_session_path, method: :delete) %>
<% else %>
  <%= link_to('Log In', new_user_session_path) %>
<% end %>

app/views/domains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Domain name:</strong>
  <%= @domain.domain_name %>
</p>

<p>
  <strong>Period:</strong>
  <%= @domain.period %>
</p>

<p>
  <strong>Registration date:</strong>
  <%= @domain.registration_date %>
</p>

<p>
  <strong>Expiration date:</strong>
  <%= @domain.expiration_date %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @domain.user.first_name %>
</p>

<p>
  <strong>Registrant:</strong>
  <%= @domain.registrant_id %>
</p>

<%= link_to 'Edit', edit_domain_path(@domain) %> |
<%= link_to 'Back', domains_path %>


<br>